src/Entity/Camping.php
<?php

namespace App\Entity;

use App\Repository\CampingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CampingRepository::class)
 */
class Camping
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="champ obligatoire")
     */
    private $nom;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_fin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="champ obligatoire")
     */
    private $lieu;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="champ obligatoire")
      * @Assert\Length(
     *      min = 10,
     *      max = 500,
     *      minMessage = "la description doit comporter au moins 10 caractères",
     *      maxMessage = "la description ne peut pas dépasser 500 caractères"
     * )
     */
    private $description;

    /**
     * @ORM\Column(type="integer", nullable=true)
     *  @Assert\Positive(message ="nombre doit etre positive")
     */
    private $nb_place;

    /**
     * @ORM\Column(type="float", nullable=true)
     *  @Assert\Positive(message ="prix doit etre positive")
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity=ReservationCamp::class, mappedBy="camping")
     */
    private $reservation;





    public function __construct()
    {
        $this->res = new ArrayCollection();
        $this->reservation = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(?string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNbPlace(): ?int
    {
        return $this->nb_place;
    }

    public function setNbPlace(?int $nb_place): self
    {
        $this->nb_place = $nb_place;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(?float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }





    public function __toString() {
        return $this->lieu;
    }

    /**
     * @return Collection|ReservationCamp[]
     */
    public function getReservation(): Collection
    {
        return $this->reservation;
    }

    public function addReservation(ReservationCamp $reservation): self
    {
        if (!$this->reservation->contains($reservation)) {
            $this->reservation[] = $reservation;
            $reservation->setCamping($this);
        }

        return $this;
    }

    public function removeReservation(ReservationCamp $reservation): self
    {
        if ($this->reservation->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getCamping() === $this) {
                $reservation->setCamping(null);
            }
        }

        return $this;
    }






}

src/Form/CampingType.php
<?php

namespace App\Form;

use App\Entity\Camping;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CampingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('date_debut')
            ->add('date_fin')
            ->add('lieu')
            ->add('description')
            ->add('nb_place')
            ->add('prix')
            ->add('image', FileType::class, [
                'mapped' => false,
                'required' => false,

            ])
            ->add('save',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Camping::class,
        ]);
    }
}

src/Controller/CampingController.php
<?php

namespace App\Controller;

use App\Entity\Camping;
use App\Entity\Event;
use App\Form\CampingType;
use App\Form\EventType;
use App\Repository\CampingRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\UploadedFile;


/**
 * @Route("/camping")
 */
class CampingController extends AbstractController
{
    /**
     * @Route("/admin", name="camping_index", methods={"GET"})
     */
    public function index(CampingRepository $campingRepository,Request $request,PaginatorInterface $paginator): Response
    {
        $donnees = $this->getDoctrine()->getRepository(Camping::class)->findAll();
        $camping = $paginator->paginate(
            $donnees,
            $request->query->getInt('page',1),
            1
        );
        return $this->render('camping/index.html.twig', [
            'campings' => $camping,
        ]);
    }
    /**
 * @Route("/home", name="camping_index_home", methods={"GET"})
 */
    public function indexhome(CampingRepository $campingRepository,Request $request,PaginatorInterface $paginator): Response
    {
        $donnees = $this->getDoctrine()->getRepository(Camping::class)->findAll();
        $camping = $paginator->paginate(
            $donnees,
            $request->query->getInt('page',1),
            4
        );
        return $this->render('camping/homecamping.html.twig', [
            'campings' => $camping,
        ]);
    }

    /**
     * @Route("/partenaire", name="camping_index_part", methods={"GET"})
     */
    public function indexpart(CampingRepository $campingRepository,Request $request,PaginatorInterface $paginator): Response
    {
        $donnees = $this->getDoctrine()->getRepository(Camping::class)->findAll();
        $camping = $paginator->paginate(
            $donnees,
            $request->query->getInt('page',1),
            4
        );
        return $this->render('camping/profile.html.twig', [
            'campings' => $camping,
        ]);
    }

    /**
     * @Route("/new", name="camping_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $camp = new Camping();
        $form = $this->createForm(CampingType::class, $camp);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $uploadedFile = $form['image']->getData();
            if ($uploadedFile) {
                $destination = $this->getParameter('kernel.project_dir') . '/public/uploadcamp';
                $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
                $newFilename = $originalFilename. '-' . uniqid() . '.' . $uploadedFile->guessExtension();
                $uploadedFile->move(
                    $destination,
                    $newFilename);
                $camp->setImage($newFilename);

            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($camp);
            $entityManager->flush();

            return $this->redirectToRoute('camping_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('camping/new.html.twig', [
            'event' => $camp,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/new/part", name="camping_new_part", methods={"GET","POST"})
     */
    public function newpart(Request $request): Response
    {
        $camp = new Camping();
        $form = $this->createForm(CampingType::class, $camp);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $uploadedFile = $form['image']->getData();
            if ($uploadedFile) {
                $destination = $this->getParameter('kernel.project_dir') . '/public/uploadcamp';
                $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
                $newFilename = $originalFilename. '-' . uniqid() . '.' . $uploadedFile->guessExtension();
                $uploadedFile->move(
                    $destination,
                    $newFilename);
                $camp->setImage($newFilename);

            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($camp);
            $entityManager->flush();

            return $this->redirectToRoute('camping_index_part', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('camping/ajouter_part.html.twig', [
            'event' => $camp,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("admin/{id}", name="camping_show", methods={"GET"})
     */
    public function show(Camping $camping): Response
    {
        return $this->render('camping/show.html.twig', [
            'camping' => $camping,
        ]);
    }

    /**
     * @Route("part/{id}", name="camping_show_part", methods={"GET"})
     */
    public function showpart(Camping $camping): Response
    {
        return $this->render('camping/homedetail.html.twig', [
            'camping' => $camping,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="camping_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Camping $camping): Response
    {
        $form = $this->createForm(CampingType::class, $camping);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('camping_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('camping/edit.html.twig', [
            'camping' => $camping,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit/part", name="camping_edit_part", methods={"GET","POST"})
     */
    public function editpart(Request $request, Camping $camping): Response
    {
        $form = $this->createForm(CampingType::class, $camping);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('camping_index_part', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('camping/edit_part.html.twig', [
            'camping' => $camping,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete/{id}", name="camping_delete")
     */
    public function deletecampadmin(Request $request,$id)
    {

        $result=$this->getDoctrine()->getRepository(Camping::class)->find($id);

        $entityManager=$this->getDoctrine()->getManager();
        $entityManager->remove($result);
        $entityManager->flush();
        $response = new Response();
        $response->send();
        return $this->redirectToRoute('camping_index');


    }
    /**
     * @Route("part/delete/{id}", name="camping_delete_part")
     */
    public function deletecamppart(Request $request,$id)
    {

        $result=$this->getDoctrine()->getRepository(Camping::class)->find($id);

        $entityManager=$this->getDoctrine()->getManager();
        $entityManager->remove($result);
        $entityManager->flush();
        $response = new Response();
        $response->send();
        return $this->redirectToRoute('camping_index_part');


    }
}

templates/camping/_delete_form.html.twig
<form method="post" action="{{ path('camping_delete', {'id': camping.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ camping.id) }}">
    <button class="btn">Delete</button>
</form>

templates/camping/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/camping/ajouter_part.html.twig
{% extends 'base-front.html.twig' %}
{% block title %}ajouter event{% endblock %}
{% block body %}

    <div class="main-panel">
        <div class="content-wrapper">

            <div class="card">
                <div class="card-body">

                    <h4 style="color:#FFA500"  class="card-title">Ajouter évènements</h4>

                    {{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
                    {{form_widget(form)}}
                    {{form_end(form)}}
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
    </div>
    </section>
{% endblock %}

templates/camping/edit.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Modifier Camping{% endblock %}
{% block body %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <h4 style="color:#FFA500"  class="card-title">Modifier Camping</h4>

                        {{form_start(form ,{'attr':{'class':'form-horizontal'}})}}
                        {{form_widget(form)}}
                        {{form_end(form)}}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/camping/edit_part.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}Modifier évènement{% endblock %}
{% block body %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <h4 style="color:#FFA500"  class="card-title">Modifier évènement</h4>

                        {{form_start(form ,{'attr':{'class':'form-horizontal'}})}}
                        {{form_widget(form)}}
                        {{form_end(form)}}


                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/camping/homecamping.html.twig
{% extends 'base-front.html.twig' %}
{% block body %}
    <section class="d-flex align-items-center dark-overlay bg-cover"
             style="background-image: url('{{  asset("img/eventum.png") }}');">
        <div class="container py-6 py-lg-7 text-white overlay-content text-center">
            <div class="row">
                <div class="col-xl-10 mx-auto">
                    <h1 class="display-3 font-weight-bold text-shadow"><br></h1>
                    <p class="text-lg text-shadow"><br></p>
                </div>

            </div>
        </div>

    </section>

    <section class="py-6 bg-gray-100">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-8">
                    <p class="subtitle text-secondary">Camping</p>
                    <h2>Liste des Campings </h2>
                </div>
                <div class="col-md-4 d-md-flex align-items-center justify-content-end"><a class="text-muted text-sm" href="blog.html">
                       <i class=""></i></a></div>
            </div>
            <div class="row">
                <!-- blog item-->

                <!-- blog item-->
                {% for camp in campings %}
                    <!-- blog item-->
                    <div class="col-lg-3   hover-animate">
                        <div class="card shadow border-0 h-100"><a href="post.html"><img class="img-fluid card-img-top" src="{{ asset( 'uploadcamp/'~camp.image)}}" alt="..."/></a>
                            <div class="card-body"><a class="text-uppercase text-muted text-sm letter-spacing-2" href="#">{{ camp.nom }} </a>
                                <h5 class="my-2"><a class="text-dark" href="post.html">{{ camp.lieu }}         </a></h5>
                                <p class="text-gray-500 text-sm my-3"><i class="far fa-clock mr-2"></i>{{ camp.dateFin ? camp.dateFin|date('Y-m-d') : '' }}</p>
                                <p class="my-2 text-muted text-sm"></p><a class="btn btn-link pl-0" href="{{ path('camping_show_part', {'id': camp.id}) }}">Info<i class="fa fa-long-arrow-alt-right ml-2"></i></a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        {{ knp_pagination_render(campings) }}
    </section>




    </div>
    </div>

{% endblock %}

templates/camping/homedetail.html.twig
{% extends 'base-front.html.twig' %}
{% block title %}camping{% endblock %}
{% block body %}

    <!-- Hero Section-->
    <section class="pt-7 pb-5 d-flex align-items-end dark-overlay bg-cover" style="background-image: url('{{ asset("img/eventum.png") }}');>
        <div class="container overlay-content">
            <div class="d-flex justify-content-between align-items-start flex-column flex-lg-row align-items-lg-end">
                <div class="text-white mb-4 mb-lg-0">
                    <div class="badge badge-pill badge-transparent px-3 py-2 mb-4">{{ camping.nbPlace }}</div>
                    <h1 class="text-shadow verified">{{ camping.nom }}</h1>
                    <p><i class="fa-map-marker-alt fas mr-2"></i> {{ camping.lieu }}</p>
                    <p class="mb-0 d-flex align-items-center"><i class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-gray-200 mr-4">                   </i></p>
                </div>
            </div>
        </div>
    </section>
    <a type="button" class="btn btn-primary" href="{{ path('reservation_camp_new' ,{ 'id': camping.id })}}">Réserver</a></div>

    <section class="py-6">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <!-- About Listing-->

                    <div class="text-block">
                        <!-- Listing Location-->

                        <div class="map-wrapper-300 mb-3">
                            <div class="h-100"  id="detailMap"></div>
                            <img style=" display: block;
                      margin-left: auto;
                      margin-right: auto;
                      width: 50%;"  src="{{ asset( 'uploadcamp/'~camping.image)}}"  />
                        </div>
                    </div>



                </div>
                <div class="col-lg-4">
                    <div class="pl-xl-4">
                        <!-- Opening Hours      -->
                        <div class="card border-0 shadow mb-5">
                            <div class="card-header bg-gray-100 py-4 border-0">
                                <div class="media align-items-center">
                                    <div class="media-body">
                                        <p class="subtitle text-sm text-primary">Opening in minutes</p>
                                        <h4 class="mb-0">Opening Hours </h4>
                                    </div>
                                    <svg class="svg-icon svg-icon svg-icon-light w-3rem h-3rem ml-3 text-muted">
                                        <use xlink:href="#wall-clock-1"> </use>
                                    </svg>
                                </div>
                            </div>
                            <div class="card-body">
                                <table class="table text-sm mb-0">
                                    <tr>
                                        <th class="pl-0 border-0">DATE de debut</th>
                                        <td class="pr-0 text-right border-0">{{ camping.dateDebut ? camping.dateDebut|date('Y-m-d') : '' }}</td>
                                    </tr>
                                    <tr>
                                        <th class="pl-0">Date de fin</th>
                                        <td class="pr-0 text-right">{{ camping.dateFin ? camping.dateFin|date('Y-m-d') : '' }}</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <!-- Contact-->
                        <div class="card border-0 shadow mb-5">
                            <div class="card-header bg-gray-100 py-4 border-0">
                                <div class="media align-items-center">
                                    <div class="media-body">
                                        <p class="subtitle text-sm text-primary">Drop Us a Line</p>
                                        <h4 class="mb-0">Contact</h4>
                                    </div>
                                    <svg class="svg-icon svg-icon svg-icon-light w-3rem h-3rem ml-3 text-muted">
                                        <use xlink:href="#fountain-pen-1"> </use>
                                    </svg>
                                </div>
                            </div>
                            <div class="card-body">
                                <ul class="list-unstyled mb-4">
                                    <li class="mb-2"> <a class="text-gray-00 text-sm text-decoration-none" href="#"><i class="fa fa-phone mr-3"></i><span class="text-muted">(+216) 99 999 999</span></a></li>
                                    <li class="mb-2"> <a class=" text-sm text-decoration-none" href="#"><i class="fa fa-envelope mr-3"></i><span class="text-muted">eventum@esprit.tn</span></a></li>
                                    <li class="mb-2"> <a class=" text-sm text-decoration-none" href="#"><i class="fa fa-globe mr-3"></i><span class="text-muted">www.eventum.com</span></a></li>
                                    <li class="mb-2"> <a class="text-blue text-sm text-decoration-none" href="#"><i class="fab fa-facebook mr-3"></i><span class="text-muted">Facebook</span></a></li>
                                    <li class="mb-2"> <a class=" text-sm text-decoration-none" href="#"><i class="fab fa-twitter mr-3"></i><span class="text-muted">Twitter</span></a></li>
                                    <li class="mb-2"> <a class=" text-sm text-decoration-none" href="#"><i class="fab fa-instagram mr-3"></i><span class="text-muted">Instagram</span></a></li>
                                    <li class="mb-2"> <a class=" text-sm text-decoration-none" href="#"><i class="fab fa-google-plus mr-3"></i><span class="text-muted">Google+</span></a></li>
                                </ul>
                                <div class="text-center"><a class="btn btn-outline-primary btn-block" href="#"> <i class="far fa-paper-plane mr-2"></i>Send a Message</a></div>
                            </div>
                        </div>
                        <div class="text-center">
                            <p><a class="text-secondary" href="#"> <i class=""></i> </a></p><span> </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/camping/index.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Event{% endblock %}
{% block body %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 style="color:#FFA500"  class="card-title"> Liste des camping</h4>
                    <a   class="btn btn-warning btn-fw"      href="{{path ('camping_new') }}" >+ Ajouter</a>
                    <ul class="navbar-nav w-100">
                        <li class="nav-item w-100">
                            <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search">
                                <input type="text" id="myInput" alt="" onkeyup="myFunction()" class="form-control" placeholder="...">
                            </form>
                        </li>

                                                <table class="table">
                                                    <thead>
                                                        <tr>
                                                            <th>Id</th>
                                                            <th>Nom</th>
                                                            <th>Date_debut</th>
                                                            <th>Date_fin</th>
                                                            <th>Lieu</th>



                                                            <th>actions</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                    {% for camping in campings %}
                                                        <tr>
                                                            <td>{{ camping.id }}</td>
                                                            <td>{{ camping.nom }}</td>
                                                            <td>{{ camping.dateDebut ? camping.dateDebut|date('Y-m-d') : '' }}</td>
                                                            <td>{{ camping.dateFin ? camping.dateFin|date('Y-m-d') : '' }}</td>
                                                            <td>{{ camping.lieu  }}</td>
                                                            <td>

                                                            <td><label class="badge badge-danger"> <a href="{{ path('camping_delete', {'id': camping.id}) }}"><i class="mdi mdi-delete"></i></a></label><label class="badge badge-info"><a href="{{ path('camping_edit', {'id': camping.id}) }}"><i class="mdi mdi-table-edit"></i></a></label><label class="badge badge-warning"><a href="{{ path('camping_show', {'id': camping.id}) }}"><i class="mdi mdi-information-outline"></i></a></label></td>
                                                            </td>
                                                        </tr>
                                                    {% else %}
                                                        <tr>
                                                            <td colspan="10">no records found</td>
                                                        </tr>
                                                    {% endfor %}
                                                    </tbody>
                                                </table>
                        {{ knp_pagination_render(campings) }}
                </div>

            </div>
        </div>
    </div>
</div>
    </div>
{% endblock %}

templates/camping/new.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}ajouter camping{% endblock %}

{% block body %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <h4 style="color:#FFA500"  class="card-title">Ajouter camping</h4>

                        {{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
                        {{form_widget(form)}}
                        {{form_end(form)}}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/camping/show.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Camping{% endblock %}

{% block body %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 style="color:#FFA500"  class="card-title">Camping</h4>



    <table class="table">
        <tbody>

            <tr>
                <th>Nom</th>
                <td>{{ camping.nom }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ camping.dateDebut ? camping.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ camping.dateFin ? camping.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Lieu</th>
                <td>{{ camping.lieu }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ camping.description }}</td>
            </tr>
            <tr>
                <th>Nb_place</th>
                <td>{{ camping.nbPlace }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ camping.prix }}</td>
            </tr>
            <tr>

                 <img style=" display: block;
                      margin-left: auto;
                      margin-right: auto;
                      width: 50%;"  src="{{ asset( 'uploadcamp/'~camping.image)}}"  />
            </tr>
        </tbody>
    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}